export enum AJVSchemaEnum {
  QueryCertReq = 'QueryCertReq',
  InjectTxReq = 'InjectTxReq',
  PenaltyTx = 'PenaltyTx',
  InternalTxBase = 'InternalTxBase',
  LeftNetworkEarlyViolationData = 'LeftNetworkEarlyViolationData',
  SyncingTimeoutViolationData = 'SyncingTimeoutViolationData',
  NodeRefutedViolationData = 'NodeRefutedViolationData',
  Sign = 'Sign',
  AppJoinData = 'AppJoinData',
  StakeResp = 'StakeResp',
  StakeCert = 'StakeCert',
  RemoveNodeCert = 'RemoveNodeCert',
  InitNetworkTx = 'InitNetworkTx',
  ApplyChangeConfigTx = 'ApplyChangeConfigTx',
  ApplyNetworkParamTx = 'ApplyNetworkParamTx',
  ChangeConfigTx = 'ChangeConfigTx',
  ChangeNetworkParamTx = 'ChangeNetworkParamTx',
  SetCertTimeTx = 'SetCertTimeTx',
  StakeTx = 'StakeTx',
  UnstakeTx = 'UnstakeTx',
  TransferFromSecureAccountTx = 'TransferFromSecureAccountTx',
  ClaimRewardTx = 'ClaimRewardTx',
  NodeRewardTxData = 'NodeRewardTxData',
  NodeInitTxData = 'NodeInitTxData',
  InitRewardTimesTx = 'InitRewardTimesTx',
}
